elasticsearch:
  image: registry.docker.sce.sina.com/deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
logstash:
  image: registry.docker.sce.sina.com/deviantony/elk-logstash
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
kibana3:
  image: registry.docker.sce.sina.com/deviantony/elk-kibana:kibana3
  ports:
    - "8080:80"
  links:
    - elasticsearch
kibana4:
  image: registry.docker.sce.sina.com/deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
